//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.WSDLservicereference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/WsdlServices")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantDetails", Namespace="http://schemas.datacontract.org/2004/07/WsdlServices")]
    [System.SerializableAttribute()]
    public partial class RestaurantDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WsdlServices")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestaurantNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestaurantName {
            get {
                return this.RestaurantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantNameField, value) != true)) {
                    this.RestaurantNameField = value;
                    this.RaisePropertyChanged("RestaurantName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryDeatils", Namespace="http://schemas.datacontract.org/2004/07/WsdlServices")]
    [System.SerializableAttribute()]
    public partial class DeliveryDeatils : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDLservicereference.IWsdlServices")]
    public interface IWsdlServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetMenu", ReplyAction="http://tempuri.org/IWsdlServices/GetMenuResponse")]
        System.Collections.Generic.Dictionary<string, double> GetMenu(string restaurantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetMenu", ReplyAction="http://tempuri.org/IWsdlServices/GetMenuResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetMenuAsync(string restaurantId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/AddToCart", ReplyAction="http://tempuri.org/IWsdlServices/AddToCartResponse")]
        void AddToCart(string itemName, double price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/AddToCart", ReplyAction="http://tempuri.org/IWsdlServices/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(string itemName, double price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ViewCart", ReplyAction="http://tempuri.org/IWsdlServices/ViewCartResponse")]
        TryIt.WSDLservicereference.CartItem[] ViewCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ViewCart", ReplyAction="http://tempuri.org/IWsdlServices/ViewCartResponse")]
        System.Threading.Tasks.Task<TryIt.WSDLservicereference.CartItem[]> ViewCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetTotalAmount", ReplyAction="http://tempuri.org/IWsdlServices/GetTotalAmountResponse")]
        double GetTotalAmount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetTotalAmount", ReplyAction="http://tempuri.org/IWsdlServices/GetTotalAmountResponse")]
        System.Threading.Tasks.Task<double> GetTotalAmountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ApplyCoupon", ReplyAction="http://tempuri.org/IWsdlServices/ApplyCouponResponse")]
        double ApplyCoupon(string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ApplyCoupon", ReplyAction="http://tempuri.org/IWsdlServices/ApplyCouponResponse")]
        System.Threading.Tasks.Task<double> ApplyCouponAsync(string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/PlaceOrder", ReplyAction="http://tempuri.org/IWsdlServices/PlaceOrderResponse")]
        void PlaceOrder(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/PlaceOrder", ReplyAction="http://tempuri.org/IWsdlServices/PlaceOrderResponse")]
        System.Threading.Tasks.Task PlaceOrderAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ReviewAndRate", ReplyAction="http://tempuri.org/IWsdlServices/ReviewAndRateResponse")]
        string ReviewAndRate(int value, string lateornot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/ReviewAndRate", ReplyAction="http://tempuri.org/IWsdlServices/ReviewAndRateResponse")]
        System.Threading.Tasks.Task<string> ReviewAndRateAsync(int value, string lateornot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/DoPayment", ReplyAction="http://tempuri.org/IWsdlServices/DoPaymentResponse")]
        string DoPayment(string cardNumber, string expiry, string CVV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/DoPayment", ReplyAction="http://tempuri.org/IWsdlServices/DoPaymentResponse")]
        System.Threading.Tasks.Task<string> DoPaymentAsync(string cardNumber, string expiry, string CVV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/NotifyPayment", ReplyAction="http://tempuri.org/IWsdlServices/NotifyPaymentResponse")]
        void NotifyPayment(string emailId, string restaurantName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/NotifyPayment", ReplyAction="http://tempuri.org/IWsdlServices/NotifyPaymentResponse")]
        System.Threading.Tasks.Task NotifyPaymentAsync(string emailId, string restaurantName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetRestaurantsByAddress", ReplyAction="http://tempuri.org/IWsdlServices/GetRestaurantsByAddressResponse")]
        TryIt.WSDLservicereference.RestaurantDetails[] GetRestaurantsByAddress(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetRestaurantsByAddress", ReplyAction="http://tempuri.org/IWsdlServices/GetRestaurantsByAddressResponse")]
        System.Threading.Tasks.Task<TryIt.WSDLservicereference.RestaurantDetails[]> GetRestaurantsByAddressAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/StoreOrder", ReplyAction="http://tempuri.org/IWsdlServices/StoreOrderResponse")]
        void StoreOrder(string orderId, string customerName, string restaurantName, string customerAddress, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/StoreOrder", ReplyAction="http://tempuri.org/IWsdlServices/StoreOrderResponse")]
        System.Threading.Tasks.Task StoreOrderAsync(string orderId, string customerName, string restaurantName, string customerAddress, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/LoadOrders", ReplyAction="http://tempuri.org/IWsdlServices/LoadOrdersResponse")]
        TryIt.WSDLservicereference.Order[] LoadOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/LoadOrders", ReplyAction="http://tempuri.org/IWsdlServices/LoadOrdersResponse")]
        System.Threading.Tasks.Task<TryIt.WSDLservicereference.Order[]> LoadOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetDeliveryDetails", ReplyAction="http://tempuri.org/IWsdlServices/GetDeliveryDetailsResponse")]
        TryIt.WSDLservicereference.DeliveryDeatils GetDeliveryDetails(string userAddress, string restaurantAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsdlServices/GetDeliveryDetails", ReplyAction="http://tempuri.org/IWsdlServices/GetDeliveryDetailsResponse")]
        System.Threading.Tasks.Task<TryIt.WSDLservicereference.DeliveryDeatils> GetDeliveryDetailsAsync(string userAddress, string restaurantAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsdlServicesChannel : TryIt.WSDLservicereference.IWsdlServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsdlServicesClient : System.ServiceModel.ClientBase<TryIt.WSDLservicereference.IWsdlServices>, TryIt.WSDLservicereference.IWsdlServices {
        
        public WsdlServicesClient() {
        }
        
        public WsdlServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsdlServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsdlServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsdlServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, double> GetMenu(string restaurantId) {
            return base.Channel.GetMenu(restaurantId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetMenuAsync(string restaurantId) {
            return base.Channel.GetMenuAsync(restaurantId);
        }
        
        public void AddToCart(string itemName, double price, int quantity) {
            base.Channel.AddToCart(itemName, price, quantity);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(string itemName, double price, int quantity) {
            return base.Channel.AddToCartAsync(itemName, price, quantity);
        }
        
        public TryIt.WSDLservicereference.CartItem[] ViewCart() {
            return base.Channel.ViewCart();
        }
        
        public System.Threading.Tasks.Task<TryIt.WSDLservicereference.CartItem[]> ViewCartAsync() {
            return base.Channel.ViewCartAsync();
        }
        
        public double GetTotalAmount() {
            return base.Channel.GetTotalAmount();
        }
        
        public System.Threading.Tasks.Task<double> GetTotalAmountAsync() {
            return base.Channel.GetTotalAmountAsync();
        }
        
        public double ApplyCoupon(string couponCode) {
            return base.Channel.ApplyCoupon(couponCode);
        }
        
        public System.Threading.Tasks.Task<double> ApplyCouponAsync(string couponCode) {
            return base.Channel.ApplyCouponAsync(couponCode);
        }
        
        public void PlaceOrder(string emailAddress) {
            base.Channel.PlaceOrder(emailAddress);
        }
        
        public System.Threading.Tasks.Task PlaceOrderAsync(string emailAddress) {
            return base.Channel.PlaceOrderAsync(emailAddress);
        }
        
        public string ReviewAndRate(int value, string lateornot) {
            return base.Channel.ReviewAndRate(value, lateornot);
        }
        
        public System.Threading.Tasks.Task<string> ReviewAndRateAsync(int value, string lateornot) {
            return base.Channel.ReviewAndRateAsync(value, lateornot);
        }
        
        public string DoPayment(string cardNumber, string expiry, string CVV) {
            return base.Channel.DoPayment(cardNumber, expiry, CVV);
        }
        
        public System.Threading.Tasks.Task<string> DoPaymentAsync(string cardNumber, string expiry, string CVV) {
            return base.Channel.DoPaymentAsync(cardNumber, expiry, CVV);
        }
        
        public void NotifyPayment(string emailId, string restaurantName) {
            base.Channel.NotifyPayment(emailId, restaurantName);
        }
        
        public System.Threading.Tasks.Task NotifyPaymentAsync(string emailId, string restaurantName) {
            return base.Channel.NotifyPaymentAsync(emailId, restaurantName);
        }
        
        public TryIt.WSDLservicereference.RestaurantDetails[] GetRestaurantsByAddress(string address) {
            return base.Channel.GetRestaurantsByAddress(address);
        }
        
        public System.Threading.Tasks.Task<TryIt.WSDLservicereference.RestaurantDetails[]> GetRestaurantsByAddressAsync(string address) {
            return base.Channel.GetRestaurantsByAddressAsync(address);
        }
        
        public void StoreOrder(string orderId, string customerName, string restaurantName, string customerAddress, double amount) {
            base.Channel.StoreOrder(orderId, customerName, restaurantName, customerAddress, amount);
        }
        
        public System.Threading.Tasks.Task StoreOrderAsync(string orderId, string customerName, string restaurantName, string customerAddress, double amount) {
            return base.Channel.StoreOrderAsync(orderId, customerName, restaurantName, customerAddress, amount);
        }
        
        public TryIt.WSDLservicereference.Order[] LoadOrders() {
            return base.Channel.LoadOrders();
        }
        
        public System.Threading.Tasks.Task<TryIt.WSDLservicereference.Order[]> LoadOrdersAsync() {
            return base.Channel.LoadOrdersAsync();
        }
        
        public TryIt.WSDLservicereference.DeliveryDeatils GetDeliveryDetails(string userAddress, string restaurantAddress) {
            return base.Channel.GetDeliveryDetails(userAddress, restaurantAddress);
        }
        
        public System.Threading.Tasks.Task<TryIt.WSDLservicereference.DeliveryDeatils> GetDeliveryDetailsAsync(string userAddress, string restaurantAddress) {
            return base.Channel.GetDeliveryDetailsAsync(userAddress, restaurantAddress);
        }
    }
}
